language: ruby
rvm:
  - 2.0.0
env:
  - DB=postgresql
before_script:
  - psql -c "CREATE USER initialProject WITH PASSWORD '123456';" -U postgres
  - rake db:create
  - rake db:migrate
  - rake db:test:prepare
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec spec